language: php

php:
  - 7.4

before_script:
  - composer install
  - composer dump-autoload
  - cp vendor/spatie/laravel-permission/config/permission.php vendor/orchestra/testbench-core/laravel/config/permission.php
  - vendor/bin/testbench cache:clear
  - vendor/bin/testbench config:clear

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
